export const BASE_URL = 'https://www.googleapis.com/youtube/v3'
export const API_KEY = 'AIzaSyBkV9ea_vdXr0BtngYLGvmvHJYolWHlI9Y'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const FETCH_VIDEOS = 'FETCH_VIDEOS'
export const SELECT_VIDEO = 'SELECT_VIDEO'
